void
baz(integer i, text &exception)
{
    exception = cat("U", itoa(i));
    error(exception);
}

void
bar(integer i, text &exception)
{
    baz(i, exception);
}

void
foo(void)
{
    integer i;

    i = 0;
    while (i < 2) {
	text e;

	if (trap(bar, i, e)) {
	    o_text("Exception `");
	    o_text(e);
	    o_text("' thrown\n");
	    if (!compare(e, "U1")) {
		o_text("will not catch exception\n");
		error(e);
	    }
	}
	i += 1;
    }

    o_text("Never reached.\n");
}

integer
main(void)
{
    foo();

    return 0;
}
