{{Control Structures}}
This task is to give an example of an exception handling routine and to "throw" a new exception.

Cf. [[Exceptions Through Nested Calls]]
